name: desktop_webview_window
description: Show a webview window on your flutter desktop application.
version: 0.2.2
homepage: https://github.com/dIvYaNshhh/desktop_webview_window

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DesktopWebviewWindowPlugin
      windows:
        pluginClass: DesktopWebviewWindowPlugin
      linux:
        pluginClass: DesktopWebviewWindowPlugin
